document.write("<script language='javascript' src='http://10.72.118.19/arcgis_js_api/library/3.18/init.js'></script>");
document.write("<script language='javascript' src='js/jquery-1.7.2.js'></script>");
document.write("<script language='javascript' src='js/initMap.js'></script>");
document.write("<script language='javascript' src='js/common.js'></script>");
document.write("<script language='javascript' src='js/measure.js'></script>");
document.write("<script language='javascript' src='js/geometryQuery.js'></script>");
document.write("<script language='javascript' src='js/keywordsQuery.js'></script>");
document.write("<script language='javascript' src='js/jstree/jtree.js'></script>");
document.write("<script language='javascript' src='js/jstree/layerControl.js'></script>");